CREATE DATABASE IF NOT EXISTS cards;
USE cards;
CREATE TABLE cards(
    ID VARCHAR(36) DEFAULT (UUID()) NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    HP INT UNSIGNED NOT NULL,
    FIRST_EDITION BOOL NOT NULL,
    EXPANSION VARCHAR(55) NOT NULL,
    KIND VARCHAR(55) NOT NULL,
    RARITY VARCHAR(55) NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    STRANGENESS VARCHAR(55) NOT NULL,
    IMAGE VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP NULL DEFAULT NULL
);